-- 강의 가능 과목.sql
-- tblAvailableSubject
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 1);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 3);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 7);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 11);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 13);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 16);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 50);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 25);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 30);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 1, 42);

-- 2 곽우신 1 3 4 33 24 12 44 23  10
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 3);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 4);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 33);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 24);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 12);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 44);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 23);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 2, 10);


-- 3 이응수 10  1  21 11 18 16 2 6
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 10);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 1);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 21);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 11);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 18);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 16);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 2);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 3, 6);

-- 4 이창익 32 8 16 24 27 36 37 42 48 12
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 32);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 8);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 16);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 24);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 27);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 36);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 37);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 42);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 48);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 4, 12);
insert into TBLAVAILABLESUBJECT 
values (111, 4, 6);
insert into TBLAVAILABLESUBJECT
values (112, 4, 10);
insert into TBLAVAILABLESUBJECT
values (113, 4, 49);
insert into TBLAVAILABLESUBJECT
values (114, 4, 50);
insert into TBLAVAILABLESUBJECT
values (115, 4, 24);
insert into TBLAVAILABLESUBJECT
values (116, 4, 38);    
    
-- 5 박세인 7 11 16 29 32  50 24 22 14
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 7);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 11);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 16);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 29);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 32);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 50);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 24);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 22);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 5, 14);
    
-- 6 이규미 23 2 5 9 14 18 23  49
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 23);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 2);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 5);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 9);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 14);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 18);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 23);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 6, 49);
--
-- [대기] 강의가능과목에만 들어가면 된다.
-- 7 김호진 42 12 18 23 40
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 7, 42);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 7, 12);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 7, 18);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 7, 23);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 7, 40);
    
-- 8 김현룡 22 11 13 15 43
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 8, 22);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 8, 11);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 8, 13);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 8, 15);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 8, 43);
    
-- 9 김대기 16 24 28 35 39
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 9, 16);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 9, 24);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 9, 28);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 9, 35);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 9, 39);
    
-- 10 한장희 12 16 23 29 31
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 10, 12);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 10, 16);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 10, 23);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 10, 29);
insert into TBLAVAILABLESUBJECT
values (SEQ_TBLAVAILABLESUBJECT.nextval, 10, 31);

