--과목
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Java 객체지향 프로그래밍 기초 및 활용', 22);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Java SE 기초 및 Network Programming', 28);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '클라우드 개발을 위한 자바 기초 프로그래밍', 22);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Java Network Programming', 21);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '객체지향과 Java SE', 9);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Java OpenJDK Programming', 29);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'JAVA 애플리케이션 구현', 18);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '객체지향 프로그래밍', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'database Programming', 10);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '오라클을 사용한 RDBMS의 SQL과 PL/SQL', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '데이터베이스 구조 설계 및 활용', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '데이터베이스 설계 및 구축', 13);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '데이터베이스 구현', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '데이터 분석기법 및 활용', 5);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Spring 서버기반의 지능형 웹 통합 개발 프로젝트 구축', 10);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Spring Framework 기반 백엔드 설계 및 구축', 13);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Back-End Server Programming', 26);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '반응형 웹 프로젝트', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Web Publishing을 위한 Front-End 설계 및 구현', 20);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '웹 애플리케이션 프로그래밍', 18);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Front_end UI/UX 구현', 13);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Server Side 프로그래밍', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '지능형 웹을 위한 애플리케이션 구축', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Front-end 애플리케이션 구현', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Spring Framework 기반 back-end 설계 및 구축', 38);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '프론트엔드 개발 기법', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '벡엔드 개발 기법', 29);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '반응형 웹 개발기법Back-end', 15);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Back-end 웹 애플리케이션 구현', 12);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'AWS 클라우드 등록 설정 및 구축', 6);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'AWS 기반 통합 프로젝트', 7);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '임베디드 애플리케이션 구현', 5);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '공공 데이터 분석기법을 활용한 데이터 융합 프로젝트', 20);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '임베디드 애플리케이션 구현', 5);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '결함 식별을 위한 애플리케이션 테스트', 3);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '클라우드 시스템 개요 및 AWS 서비스 요소', 30);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'UML을 사용한 시스템 분석', 6);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '데스크탑 UI/UX 설계', 11);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '콘텐츠 추천 알고리즘 기법', 5);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '아두이노를 활용한 임베디드 프로그래밍', 23);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '멀티 플랫폼 기반 융합 실무 프로젝트', 7);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '임베디드 애플리케이션 구현', 9);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '풀스택 융합 프로젝트', 19);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Full-stack Framework 구현', 5);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '오픈플랫폼(Arduino)을 활용한 Embedded 융합프로젝트', 14);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '애플리케이션 배포', 5);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '융합기반 웹표준 프로젝트', 24);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, '콘텐츠 추천 알고리즘 기법', 5);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Front-end 클라이언트 화면설계 및 구현', 16);
insert into TBLSUBJECT values(SEQ_TBLSUBJECT.nextval, 'Back-end 서버프로그래밍 설계 및 구현', 28);

-- 과목 변경 (왜래키 추가)
update tblsubject set bookseq=4 where SUBJECTSEQ=2;
update tblsubject set bookseq=1 where SUBJECTSEQ=3;
update tblsubject set bookseq=1 where SUBJECTSEQ=4;
update tblsubject set bookseq=4 where SUBJECTSEQ=5;
update tblsubject set bookseq=1 where SUBJECTSEQ=6;
update tblsubject set bookseq=1 where SUBJECTSEQ=7;
update tblsubject set bookseq=4 where SUBJECTSEQ=8;
update tblsubject set bookseq=2 where SUBJECTSEQ=9;
update tblsubject set bookseq=2 where SUBJECTSEQ=10;
update tblsubject set bookseq=2 where SUBJECTSEQ=11;
update tblsubject set bookseq=2 where SUBJECTSEQ=12;
update tblsubject set bookseq=2 where SUBJECTSEQ=13;
update tblsubject set bookseq=2 where SUBJECTSEQ=14;
update tblsubject set bookseq=16 where SUBJECTSEQ=15;
update tblsubject set bookseq=25 where SUBJECTSEQ=16;
update tblsubject set bookseq=10 where SUBJECTSEQ=17;
update tblsubject set bookseq=17 where SUBJECTSEQ=18;
update tblsubject set bookseq=13 where SUBJECTSEQ=19;
update tblsubject set bookseq=19 where SUBJECTSEQ=20;
update tblsubject set bookseq=12 where SUBJECTSEQ=21;
update tblsubject set bookseq=14 where SUBJECTSEQ=22;
update tblsubject set bookseq=17 where SUBJECTSEQ=23;
update tblsubject set bookseq=13 where SUBJECTSEQ=24;
update tblsubject set bookseq=19 where SUBJECTSEQ=25;
update tblsubject set bookseq=18 where SUBJECTSEQ=26;
update tblsubject set bookseq=10 where SUBJECTSEQ=27;
update tblsubject set bookseq=10 where SUBJECTSEQ=28;
update tblsubject set bookseq=10 where SUBJECTSEQ=29;
update tblsubject set bookseq=7 where SUBJECTSEQ=30;
update tblsubject set bookseq=7 where SUBJECTSEQ=31;
update tblsubject set bookseq=22 where SUBJECTSEQ=32;
update tblsubject set bookseq=26 where SUBJECTSEQ=33;
update tblsubject set bookseq=22 where SUBJECTSEQ=34;
update tblsubject set bookseq=8 where SUBJECTSEQ=35;
update tblsubject set bookseq=7 where SUBJECTSEQ=36;
update tblsubject set bookseq=20 where SUBJECTSEQ=37;
update tblsubject set bookseq=13 where SUBJECTSEQ=38;
update tblsubject set bookseq=15 where SUBJECTSEQ=39;
update tblsubject set bookseq=22 where SUBJECTSEQ=40;
update tblsubject set bookseq=25 where SUBJECTSEQ=41;
update tblsubject set bookseq=22 where SUBJECTSEQ=42;
update tblsubject set bookseq=15 where SUBJECTSEQ=43;
update tblsubject set bookseq=15 where SUBJECTSEQ=44;
update tblsubject set bookseq=22 where SUBJECTSEQ=45;
update tblsubject set bookseq=9 where SUBJECTSEQ=46;
update tblsubject set bookseq=17 where SUBJECTSEQ=47;
update tblsubject set bookseq=15 where SUBJECTSEQ=48;
update tblsubject set bookseq=18 where SUBJECTSEQ=49;
update tblsubject set bookseq=10 where SUBJECTSEQ=50;
update tblsubject set bookseq=1 where SUBJECTSEQ=1;