-- 배점등록
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 1);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 2);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 3);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 4);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 5);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 6);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 7);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 8);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 9);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 10);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 11);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 12);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 19);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 20);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 21);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 22);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 23);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 24);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 25);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 26);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 27);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 28);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 29);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 30);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 31);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 32);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 33);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 36);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 37);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 76);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 77);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 78);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 79);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 80);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 81);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 82);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 83);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 84);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 85);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 86);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 87);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 88);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 89);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 90);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 91);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 92);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 93);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 94);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 95);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 96);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 97);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 98);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 99);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 100);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 101);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 102);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 103);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 104);
insert into tblrate(RATESEQ, ATTENDRATE, PERFORMRATE, WRITERATE, OPENSUBJECTSEQ)
VALUES (seq_tblrate.nextval, 20, 40, 40, 105);
