
-- 취업처

-- COMPANYSEQ = 회사 번호
-- COMPANYNAME = 회사명
-- CONPANYANNUALSALARY = 연봉
-- COMPANYSCALE = 회사규모
-- COMPANYAREA = 근무지역
-- WORKINGTYPE = 근무형태

INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '주성엔지니어링㈜', 3500, '대기업', '서울', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '에듀베이션(주)', 2500, '중소기업', '서울', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '아이티메세지', 2400, '중소기업', '구로', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '(주)모바일엔트로피', 2460, '중소기업', '판교', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '디케이아이테크놀러지', 2500, '중소기업', '서울', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '바이텍시스템', 2500, '중소기업', '서울', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '(주)퓨처젠', 2600, '중소기업', '판교', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '크리니티', 2600, '중소기업', '구로', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '유알피시스템', 2700, '중견기업', '서울', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '엠씨에스텍', 2400, '중소기업', '서울', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '㈜아이디룩', 2400, '중소기업', '가산', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '에이비씨솔루션', 2400, '중소기업', '서울', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '보고정보시스템', 2400, '중소기업', '구로', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '(주)슈피겐코리아', 2800, '중견기업', '구로', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '코레일네트웍스(주)', 3300, '대기업', '서울', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '쥬비스그룹', 2600, '중소기업', '구로', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '더존비즈온', 3000, '중견기업', '판교', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '직방', 2800, '중소기업', '판교', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '전주비전대학교', 2600, '중소기업', '구로', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '오픈에스지', 3000, '중견기업', '가산', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '서현커뮤니케이션', 2800, '중소기업', '가산', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, 'idoogen', 2800, '중견기업', '판교', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '엔백', 2800, '중소기업', '가산', '비정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '해커스어학원', 2600, '중소기업', '구로', '정규직');
INSERT INTO tblCompany (COMPANYSEQ,COMPANYNAME,CONPANYANNUALSALARY, COMPANYSCALE, COMPANYAREA, WORKINGTYPE) VALUES (seq_tblCompany.nextVal, '(주)SAF반도체', 3000, '대기업', '판교', '정규직');
