-- 프로젝트피드백

insert into TBLPROJECTFEEDBACK values (1,'프로젝트 마무리를 참 잘했어요');
insert into TBLPROJECTFEEDBACK values (2,'산출물을 아주 아주 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (3,'산출물을 매우 아주 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (4,'프로젝트 마무리를 매우 잘했어요');
insert into TBLPROJECTFEEDBACK values (5,'산출물을 참 아주 칭찬합니다.');
insert into TBLPROJECTFEEDBACK values (6,'프로젝트 마무리를 참 잘했어요.');
insert into TBLPROJECTFEEDBACK values (7,'알고리즘 최적화를 아주 아주 칭찬합니다');
insert into TBLPROJECTFEEDBACK values (8,'프로젝트 마무리를 정말 아주 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (9,'산출물을 참 아주 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (10,'알고리즘 최적화를 매우 아주 칭찬합니다.');
insert into TBLPROJECTFEEDBACK values (11,'프로젝트 마무리를 참 잘했어요');
insert into TBLPROJECTFEEDBACK values (12,'프로젝트 마무리를 정말 잘했어요');
insert into TBLPROJECTFEEDBACK values (13,'산출물을 아주 아주 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (14,'프로젝트 마무리를 참 잘했어요.');
insert into TBLPROJECTFEEDBACK values (15,'프로젝트 마무리를 정말 잘했어요');
insert into TBLPROJECTFEEDBACK values (16,'알고리즘 최적화를 참 잘했어요.');
insert into TBLPROJECTFEEDBACK values (17,'프로젝트 마무리를 참 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (18,'산출물을 매우 잘했어요');
insert into TBLPROJECTFEEDBACK values (19,'산출물을 아주 조금 더 다듬으세요.');
insert into TBLPROJECTFEEDBACK values (20,'프로젝트 마무리를 참 아주 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (21,'산출물을 매우 아주 칭찬합니다.');
insert into TBLPROJECTFEEDBACK values (22,'프로젝트 마무리를 정말 잘했어요');
insert into TBLPROJECTFEEDBACK values (23,'알고리즘 최적화를 참 아주 칭찬합니다');
insert into TBLPROJECTFEEDBACK values (24,'프로젝트 마무리를 매우 조금 더 다듬으세요.');
insert into TBLPROJECTFEEDBACK values (25,'프로젝트 마무리를 참 아주 칭찬합니다');
insert into TBLPROJECTFEEDBACK values (26,'산출물을 정말 잘했어요');
insert into TBLPROJECTFEEDBACK values (27,'산출물을 매우 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (28,'프로젝트 마무리를 매우 아주 멋지게 했습니다.');
insert into TBLPROJECTFEEDBACK values (29,'프로젝트 마무리를 참 아주 칭찬합니다.');
insert into TBLPROJECTFEEDBACK values (30,'알고리즘 최적화를 정말 조금 더 다듬으세요.');
